### ISSUE TITLE
Release v0.4.0

### ISSUE THREAD

**Issue by flosse** [slowtec/tokio-modbus#47]
# ToDo's:

- [x] Resolve #32 
- [x] Resolve #38
- [x] Resolve #49 
- [x] merge `server/tcp.rs` and `server/tcp_server.rs`
- [x] Update CHANGELOG
- [x] Create a migration guide
- [x] Test TCP client with real hardware ([ur20](https://github.com/slowtec/ur20-modbus))
- [x] Publish on crates.io

## Not fixed
- fix `cargo test --no-default-features --all` - see https://github.com/slowtec/tokio-modbus/issues/49#issuecomment-596096866
- Resolve #19  (moved to v0.4.1)
- Test RTU client with real hardware ([SMT100](https://github.com/slowtec/truebner-smt100))

**Comment by flosse** [comment]
@not-fl3 Can we merge `server/tcp.rs` and `server/tcp_server.rs`? For the `v0.4.0` it will be hidden by the `tcp-server-unstable` feature but for a `v0.4.1` we could release an implementation.

**Comment by not-fl3** [comment]
> @not-fl3 Can we merge `server/tcp.rs` and `server/tcp_server.rs`? For the `v0.4.0` it will be hidden by the `tcp-server-unstable` feature but for a `v0.4.1` we could release an implementation.

totally agree, having very similar `Server` and `TcpServer` structs was very confusing. 
An attempt to fix it: https://github.com/slowtec/tokio-modbus/pull/56

**Comment by OrangeTux** [comment]
Thanks for releasing v0.4.0!
