### ISSUE TITLE
Release v0.5.0

### ISSUE THREAD

**Issue by flosse** [slowtec/tokio-modbus#80]
- [x] Update to tokio v1.x #78
- [x] Clean up and reduce dependencies #81
- [x] Use `async_trait` #82 
- [x] Wait for [`tokio-serial`](https://github.com/berkowski/tokio-serial) `v5.4.0` release
- [x] Update [`CHANGELOG.md`](https://github.com/slowtec/tokio-modbus/blob/master/CHANGELOG.md)
- [x] Update [`README.md`](https://github.com/slowtec/tokio-modbus/blob/master/README.md) (including date in Copyright)
- [x] Fix badges in Cargo.toml
- [x] #89
- [x] #84
- [x] #91 
- [x] #92 
- [x] #94
- [x] #93 
- [x] Publish on [`crates.io`](https://crates.io)

**Comment by uklotzde** [comment]
How about removing `sync` from the default features?

**Comment by uklotzde** [comment]
> How about removing `sync` from the default features?

#89

**Comment by flosse** [comment]
done :)

**Comment by bootrecords** [comment]
@flosse great work, though I'd say you forgot to mention the addition of an RTU server implementation in the Changelog.

I also noticed that the traits that use `async_trait` now are also exported and can be implemented by library users, which then also have to declare `async_trait` in their usage. That shouldn't be much of an issue, since `async_trait` is already in the depencies anyway, but I guess it would help to add some documentation somewhere to explain proper usage of those traits if anyone intends to make use of them (I may set up an according PR over the weekend, given that I mainly transitioned those traits to `async_trait` in the first place)
